### PR TITLE
Refactor README.md for PGXN

### PR DESCRIPTION
**Pull request by mkgrgis**
For unifying with https://github.com/pgspider FDW documentation template and by https://github.com/ibarwick/firebird_fdw/blob/master/README.md example of advanced FDW documentation.

### CODE REVIEW

**Comment by mkgrgis** [comment]
Ping @za-arthur , any review of this PR for [PostgreSQL extension network](https://pgxn.org ) - [FDW page](https://pgxn.org/tag/foreign%20data%20wrapper/) ?

**Comment by za-arthur** [comment]
Sorry, I don't get why these changes are necessary.

**Comment by mkgrgis** [comment]
@za-arthur, new `README.md` follows more clear and unified structure which is used by READMEs in most of other PostgreSQL FDWs. This README structure is de facto better practice and you can ensure similar structure is yet used in https://github.com/pgspider/sqlite_fdw , https://github.com/pgspider/influxdb_fdw , https://github.com/pgspider/dynamodb_fdw , https://github.com/laurenz/oracle_fdw/ , https://github.com/ibarwick/firebird_fdw etc.

**Comment by za-arthur** [comment]
`parquet_fdw` is a separate project and doesn't related to those projects. It might have its own README which might be different from READMEs of other projects.

**Comment by mkgrgis** [comment]
> It might have its own README which might be different from READMEs of other projects.

Yes, of course. This was PR for less differences between forks from [pgspider](https://github.com/pgspider) project which also use this FDW as a part.

**Pull request closed without merging**
