### PR TITLE
Multifile merge strategy fix

### PR DESCRIPTION
**Pull request by trollfred**
1. Fixes sorting pathkeys
2. Introduces `force_multifile_merge` GUC variable

### CODE REVIEW

**Comment by jrogov** [comment]
See initial observation and following discussion from here: https://github.com/adjust/segmentation_api/issues/485#issuecomment-1162767603

**Comment by cabecada** [comment]
i guess we will still see sort, multifile merge reader enablement does not help skip sort.

```
create foreign table abc ( col1 int, col2 int, col3 int ) server parquet_srv options ( filename '/var/lib/postgresql/example.parquet.0 /var/lib/postgresql/example.parquet.1 /var/lib/postgresql/example.parquet.2 /var/lib/postgresql/example.parquet.3', sorted 'col2 col1 col3', files_in_order 'true');

foo=# select * from abc;
 col1 | col2 | col3 
------+------+------
   10 |  100 | 1000
   10 |  100 | 1000
   10 |  100 | 1000
   10 |  100 | 1000
   10 |  100 | 1000
   10 |  100 | 1000
   10 |  100 | 1000
   10 |  100 | 1000
   10 |  100 | 1000
   10 |  100 | 1000
   11 |  101 | 1001
   11 |  101 | 1001
   11 |  101 | 1001
   11 |  101 | 1001
   11 |  101 | 1001
   11 |  101 | 1001
   11 |  101 | 1001
   11 |  101 | 1001
   11 |  101 | 1001
   11 |  101 | 1001
   12 |  102 | 1002
   12 |  102 | 1002
   12 |  102 | 1002
   12 |  102 | 1002
   12 |  102 | 1002
   12 |  102 | 1002
   12 |  102 | 1002
   12 |  102 | 1002
   12 |  102 | 1002
   12 |  102 | 1002
   13 |  103 | 1003
   13 |  103 | 1003
   13 |  103 | 1003
   13 |  103 | 1003
   13 |  103 | 1003
   13 |  103 | 1003
   13 |  103 | 1003
   13 |  103 | 1003
   13 |  103 | 1003
   13 |  103 | 1003
(40 rows)




foo=# explain analyze select col1, col2  from abc where col1 > 1 and col2 > 1 order by col1, col2;
                                               QUERY PLAN                                               
--------------------------------------------------------------------------------------------------------
 Sort  (cost=0.45..0.46 rows=4 width=8) (actual time=0.437..0.438 rows=40 loops=1)
   Sort Key: col1, col2
   Sort Method: quicksort  Memory: 26kB
   ->  Foreign Scan on abc  (cost=0.00..0.40 rows=4 width=8) (actual time=0.273..0.427 rows=40 loops=1)
         Filter: ((col1 > 1) AND (col2 > 1))
         Reader: Multifile
         Row groups: 
           example.parquet.0: 1
           example.parquet.1: 1
           example.parquet.2: 1
           example.parquet.3: 1
 Planning Time: 21.217 ms
 Execution Time: 0.494 ms
(13 rows)

foo=# set parquet_fdw.force_multifile_merge to true;
SET
foo=# explain analyze select col1, col2  from abc where col1 > 1 and col2 > 1 order by col1, col2;
                                               QUERY PLAN                                               
--------------------------------------------------------------------------------------------------------
 Sort  (cost=0.05..0.06 rows=4 width=8) (actual time=0.424..0.428 rows=40 loops=1)
   Sort Key: col1, col2
   Sort Method: quicksort  Memory: 26kB
   ->  Foreign Scan on abc  (cost=0.00..0.00 rows=4 width=8) (actual time=0.358..0.398 rows=40 loops=1)
         Filter: ((col1 > 1) AND (col2 > 1))
         Reader: Multifile Merge
         Row groups: 
           example.parquet.0: 1
           example.parquet.1: 1
           example.parquet.2: 1
           example.parquet.3: 1
 Planning Time: 1.483 ms
 Execution Time: 0.746 ms
(13 rows)

foo=# explain analyze select col1, col2, count(*)  from abc where col1 > 1 and col2 > 1 group by col1, col2 order by col1, col2;
                                                  QUERY PLAN                                                  
--------------------------------------------------------------------------------------------------------------
 GroupAggregate  (cost=0.05..0.13 rows=4 width=16) (actual time=0.806..0.815 rows=4 loops=1)
   Group Key: col1, col2
   ->  Sort  (cost=0.05..0.06 rows=4 width=8) (actual time=0.672..0.676 rows=40 loops=1)
         Sort Key: col1, col2
         Sort Method: quicksort  Memory: 26kB
         ->  Foreign Scan on abc  (cost=0.00..0.00 rows=4 width=8) (actual time=0.625..0.645 rows=40 loops=1)
               Filter: ((col1 > 1) AND (col2 > 1))
               Reader: Multifile Merge
               Row groups: 
                 example.parquet.0: 1
                 example.parquet.1: 1
                 example.parquet.2: 1
                 example.parquet.3: 1
 Planning Time: 2.605 ms
 Execution Time: 2.118 ms
(15 rows)

```

**Comment by za-arthur** [comment]
Order of columns in your `ORDER BY` doesn't match `sorted` option.

**Comment by cabecada** [comment]
ah ok, i may be i am missing things here. you may want to add a test case for this scenario. :)

I will re read the convo in the link shared again, but if what i am testing is not the goal, and pls ignore. i found queries in the incidents similar to this, hence tested like this.

btw,
we could multifile merge with just cpu_operator_cost = 0.0000001  or worst case cpu_operator_cost = 0;
ex below.
if my predicate is not equality and ranges over many files, sort is picked up.

```
foo=# show parquet_fdw.force_multifile_merge;
 parquet_fdw.force_multifile_merge 
-----------------------------------
 false
(1 row)

foo=# explain analyze select * from abc where col1 = 10 or col1 = 13 order by col2, col3;
                                               QUERY PLAN                                                
---------------------------------------------------------------------------------------------------------
 Sort  (cost=0.41..0.42 rows=2 width=12) (actual time=1.084..1.086 rows=20 loops=1)
   Sort Key: col2, col3
   Sort Method: quicksort  Memory: 25kB
   ->  Foreign Scan on abc  (cost=0.00..0.40 rows=2 width=12) (actual time=0.821..1.064 rows=20 loops=1)
         Filter: ((col1 = 10) OR (col1 = 13))
         Rows Removed by Filter: 20
         Reader: Multifile
         Row groups: 
           example.parquet.0: 1
           example.parquet.1: 1
           example.parquet.2: 1
           example.parquet.3: 1
 Planning Time: 27.490 ms
 Execution Time: 1.156 ms
(14 rows)

foo=# set parquet_fdw.force_multifile_merge TO true;
SET
foo=# explain analyze select * from abc where col1 = 10 or col1 = 13 order by col2, col3;
                                               QUERY PLAN                                                
---------------------------------------------------------------------------------------------------------
 Sort  (cost=0.01..0.02 rows=2 width=12) (actual time=0.558..0.560 rows=20 loops=1)
   Sort Key: col2, col3
   Sort Method: quicksort  Memory: 25kB
   ->  Foreign Scan on abc  (cost=0.00..0.00 rows=2 width=12) (actual time=0.469..0.486 rows=20 loops=1)
         Filter: ((col1 = 10) OR (col1 = 13))
         Rows Removed by Filter: 20
         Reader: Multifile Merge
         Row groups: 
           example.parquet.0: 1
           example.parquet.1: 1
           example.parquet.2: 1
           example.parquet.3: 1
 Planning Time: 1.088 ms
 Execution Time: 0.909 ms
(14 rows)

foo=# set parquet_fdw.force_multifile_merge TO false;
SET

-- we can achieve the same if we just set cpu_operator_cost = 0 without this PR

foo=# explain analyze select * from abc where col1 % 2 = 0 order by col2, col3;
                                               QUERY PLAN                                                
---------------------------------------------------------------------------------------------------------
 Sort  (cost=0.41..0.42 rows=1 width=12) (actual time=0.761..0.764 rows=20 loops=1)
   Sort Key: col2, col3
   Sort Method: quicksort  Memory: 25kB
   ->  Foreign Scan on abc  (cost=0.00..0.40 rows=1 width=12) (actual time=0.327..0.732 rows=20 loops=1)
         Filter: ((col1 % 2) = 0)
         Rows Removed by Filter: 20
         Reader: Multifile
         Row groups: 
           example.parquet.0: 1
           example.parquet.1: 1
           example.parquet.2: 1
           example.parquet.3: 1
 Planning Time: 1.744 ms
 Execution Time: 0.833 ms
(14 rows)


foo=# set cpu_operator_cost TO 0;
SET
foo=# explain analyze select * from abc where col1 % 2 = 0 order by col2, col3;
                                               QUERY PLAN                                                
---------------------------------------------------------------------------------------------------------
 Sort  (cost=0.40..0.40 rows=1 width=12) (actual time=0.978..0.980 rows=20 loops=1)
   Sort Key: col2, col3
   Sort Method: quicksort  Memory: 25kB
   ->  Foreign Scan on abc  (cost=0.00..0.40 rows=1 width=12) (actual time=0.928..0.950 rows=20 loops=1)
         Filter: ((col1 % 2) = 0)
         Rows Removed by Filter: 20
         Reader: Multifile Merge
         Row groups: 
           example.parquet.0: 1
           example.parquet.1: 1
           example.parquet.2: 1
           example.parquet.3: 1
 Planning Time: 1.148 ms
 Execution Time: 1.416 ms
(14 rows)

```

**Comment by cabecada** [comment]
@za-arthur  yep, that was one of the cases i was testing. sorry for wrong order. sorry for the noise. i'll paste the relevant cases just to correct above scenario.

**Comment by cabecada** [comment]
@trollfred  so yes your use case as well as the group by option works as well (did not pick up sort) atleast for small workload.

**Comment by cabecada** [comment]
i dont have much data but

we might end up reduce number of parallel workers due to this, was my concern.


```
foo=# set parallel_tuple_cost TO 0;
SET
foo=# set force_parallel_mode TO on;
SET
foo=# set parallel_setup_cost TO 0;
SET
foo=# explain analyze select col1, col2, col3, count(*) filter (where col1 % 2 = 0)  from t1 where col1 > 1 and col2 > 1 and col3 > 0 group by col1, col2,col3 having last(col1) > 1 and last(col2) > 1 order by col1, col2, col3;
                                                                 QUERY PLAN                                                             
     
----------------------------------------------------------------------------------------------------------------------------------------
-----
 Sort  (cost=1328.26..1331.75 rows=1397 width=20) (actual time=182.465..183.567 rows=4 loops=1)
   Sort Key: col1, col2, col3
   Sort Method: quicksort  Memory: 25kB
   ->  Finalize HashAggregate  (cost=1066.67..1255.28 rows=1397 width=20) (actual time=182.436..183.556 rows=4 loops=1)
         Group Key: col1, col2, col3
         Filter: ((last(col1) > 1) AND (last(col2) > 1))
         ->  Gather  (cost=0.00..888.89 rows=11852 width=28) (actual time=153.166..183.524 rows=4 loops=1)
               Workers Planned: 4
               Workers Launched: 4
               ->  Partial GroupAggregate  (cost=0.00..888.89 rows=2963 width=28) (actual time=87.084..87.084 rows=1 loops=5)
                     Group Key: col1, col2, col3
                     ->  Parallel Foreign Scan on t1  (cost=0.00..800.00 rows=2963 width=12) (actual time=10.168..53.539 rows=80000 loop
s=5)
                           Filter: ((col1 > 1) AND (col2 > 1) AND (col3 > 0))
                           Reader: Multifile
                           Row groups: 
                             example.parquet.0: 1
                             example.parquet.1: 1
                             example.parquet.2: 1
                             example.parquet.3: 1
 Planning Time: 2.060 ms
 Execution Time: 184.073 ms
(21 rows)

foo=# set parquet_fdw.force_multifile_merge TO true;
SET
foo=# explain analyze select col1, col2, col3, count(*) filter (where col1 % 2 = 0)  from t1 where col1 > 1 and col2 > 1 and col3 > 0 group by col1, col2,col3 having last(col1) > 1 and last(col2) > 1 order by col1, col2, col3;
                                                       QUERY PLAN                                                        
-------------------------------------------------------------------------------------------------------------------------
 Gather  (cost=0.00..484.91 rows=1397 width=20) (actual time=96.929..203.626 rows=4 loops=1)
   Workers Planned: 1
   Workers Launched: 1
   Single Copy: true
   ->  GroupAggregate  (cost=0.00..484.91 rows=1397 width=20) (actual time=56.716..160.563 rows=4 loops=1)
         Group Key: col1, col2, col3
         Filter: ((last(col1) > 1) AND (last(col2) > 1))
         ->  Foreign Scan on t1  (cost=0.00..0.00 rows=14815 width=12) (actual time=10.108..111.682 rows=400000 loops=1)
               Filter: ((col1 > 1) AND (col2 > 1) AND (col3 > 0))
               Reader: Multifile Merge
               Row groups: 
                 example.parquet.0: 1
                 example.parquet.1: 1
                 example.parquet.2: 1
                 example.parquet.3: 1
 Planning Time: 1.376 ms
 Execution Time: 204.164 ms
(17 rows)
```

**Comment by cabecada** [comment]
as per the expectation of the PR to ensure multimerge files is picked up by the planner, this hack works and is also reversible incase something unexpected comes up. so lgtm.

**Review by cabecada — APPROVED** [review]
lgtm, for the specific feature in question of forcing planner to use multifile merge reader. this is just like enable_* hacks from postgres GUCs, so should be ok.

**Comment by jrogov** [comment]
@cabecada do I incorrectly remember that you've experienced crashes when using Multifile Merge (when using 1+ parallel workers?)
If it is so, how can it be good to merge, if it's prone to failures?

**Comment by jrogov** [comment]
@za-arthur waiting on your feedback on this

Either way this needs to be deployed to some server for testing with possibility of revert.

**Comment by llamanna** [comment]
Any possibility of taking care of this PR before the end of the quarter?
@za-arthur

**Comment by za-arthur** [comment]
I don't know. I'm busy with other tickets as well.

**Comment by za-arthur** [comment]
Closing this PR, since the following up PR was merged https://github.com/adjust/parquet_fdw/pull/66.

**Pull request closed without merging**
